Repository iamDyeus/tkreload, pull requests merged in 2024-10, with the labels that each got.

#9 Update README with project overview and usage instructions
  README.MD
  src/images/with.gif
  src/images/without.gif
Labels: documentation, hacktoberfest, hacktoberfest-accepted

#14 Added Logos & Previews
  .assets/logo/png/banner_dark.png
  .assets/logo/png/banner_light.png
  .assets/logo/previews/Banner (Dark).png
  .assets/logo/previews/Banner (Light).png
  .assets/logo/previews/Main (Dark.png
  .assets/logo/previews/Main (Light).png
  .assets/logo/svg/logo_dark.svg
  .assets/logo/svg/logo_light.svg
Labels: documentation, good first issue, hacktoberfest, hacktoberfest-accepted

#13 Overhauled packaging and testing
  .github/workflows/publish.yaml
  .github/workflows/test.yml
  MANIFEST.in
  README.md
  example/README.md
  pyproject.toml
  requirements.txt
  setup.py
  tkreload/__init__.py
Labels: documentation, hacktoberfest, hacktoberfest-accepted

#18 updated README.md
  README.md
Labels: documentation, good first issue, hacktoberfest, hacktoberfest-accepted

#19 feat: Use argparse instead sys.argv[..]
  tkreload/main.py
Labels: good first issue, hacktoberfest, hacktoberfest-accepted
